# Generated by Django 3.2 on 2021-05-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_privateme'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateme',
            name='room_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
