# Generated by Django 3.2 on 2021-05-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_privateme_room_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='privateme',
        ),
    ]
