# Generated by Django 3.2 on 2021-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_delete_privateme'),
    ]

    operations = [
        migrations.CreateModel(
            name='tra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('reciever', models.CharField(max_length=100)),
            ],
        ),
    ]
