# Generated by Django 3.2 on 2021-05-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_tra'),
    ]

    operations = [
        migrations.AddField(
            model_name='tra',
            name='room',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
