# Generated by Django 3.2 on 2021-05-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='group',
            field=models.CharField(max_length=100),
        ),
    ]
